// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSOY_lhLBB3RkWOgXBpgfG5k6I963M0zA',
    appId: '1:678884635945:web:3d0556441f9c45f8987338',
    messagingSenderId: '678884635945',
    projectId: 'wasselney',
    authDomain: 'wasselney.firebaseapp.com',
    storageBucket: 'wasselney.appspot.com',
    measurementId: 'G-PNS78Z4QSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzJpdub3MrmLYvLD07uDv4s2HSWqAz9RE',
    appId: '1:678884635945:android:c28a2e5f1f7a6bb7987338',
    messagingSenderId: '678884635945',
    projectId: 'wasselney',
    storageBucket: 'wasselney.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJChQXbklkVbVlYdnXuEEOYIYxfGpFJ_8',
    appId: '1:678884635945:ios:4332ce2aa0c43c12987338',
    messagingSenderId: '678884635945',
    projectId: 'wasselney',
    storageBucket: 'wasselney.appspot.com',
    iosClientId: '678884635945-qnenr8didk74eap44a8asg8e01u7277c.apps.googleusercontent.com',
    iosBundleId: 'com.example.wasselney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJChQXbklkVbVlYdnXuEEOYIYxfGpFJ_8',
    appId: '1:678884635945:ios:4332ce2aa0c43c12987338',
    messagingSenderId: '678884635945',
    projectId: 'wasselney',
    storageBucket: 'wasselney.appspot.com',
    iosClientId: '678884635945-qnenr8didk74eap44a8asg8e01u7277c.apps.googleusercontent.com',
    iosBundleId: 'com.example.wasselney',
  );
}
